[packages] quicktun: Improve QuickTun init script
The new init script won't fail if quicktun takes more than 1 second to start.

Signed-off-by: Matthias Schiffer <mschiffer@universe-factory.net>

git-svn-id: svn://svn.openwrt.org/openwrt@26488 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/packages/net/quicktun/files/quicktun.init b/packages/net/quicktun/files/quicktun.init
--- a/packages/net/quicktun/files/quicktun.init
+++ b/packages/net/quicktun/files/quicktun.init
@@ -60,12 +60,14 @@ start_service() {
 
 	eval env $OPTS "$SSD" -q -b -p "$PID" -m -x "$BIN" -S
 
-	sleep 1
+	while ! ifconfig "$interface" >/dev/null 2>&1; do
+		if ! $SSD -t -q -p $PID -x $BIN -K; then
+			echo "$s: daemon startup failed"
+			return 1
+		fi
 
-	if ! ifconfig "$interface" >/dev/null 2>&1; then
-		echo "$s: daemon startup failed"
-		return 1
-	fi
+		sleep 1
+	done
 
 	config_get up "$s" up
 	[ -n "$up" ] && sh -c "$up" - "$interface"
