switch whiterussian over to b44 and kmod-switch, use netmsg to send messages for failsafe mode (should fix #76 and #86)
git-svn-id: svn://svn.openwrt.org/openwrt@2984 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/branches/whiterussian/openwrt/package/base-files/default/etc/init.d/S10boot b/branches/whiterussian/openwrt/package/base-files/default/etc/init.d/S10boot
--- a/branches/whiterussian/openwrt/package/base-files/default/etc/init.d/S10boot
+++ b/branches/whiterussian/openwrt/package/base-files/default/etc/init.d/S10boot
@@ -11,6 +11,16 @@ sed 's/^[^#]/insmod &/' /etc/modules /etc/modules.d/* 2>&-|ash
 ifconfig lo 127.0.0.1 up
 ifconfig eth0 promisc
 
+# configure the switch based on nvram if not in failsafe mode
+[ -d /proc/switch/eth0 -a -z "$FAILSAFE" ] && {
+	for nr in `seq 0 15`; do
+		vp="$(nvram get vlan${nr}ports)"
+		[ -z "$vp" -o -z "$(nvram get vlan${nr}hwname)" ] || {
+			echo "$vp" > /proc/switch/eth0/vlan/$nr/ports
+		}
+	done
+}
+
 HOSTNAME=$(nvram get wan_hostname)
 HOSTNAME=${HOSTNAME%%.*}
 echo ${HOSTNAME:=OpenWrt}>/proc/sys/kernel/hostname
