sanity check
git-svn-id: svn://svn.openwrt.org/openwrt@3489 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/branches/whiterussian/openwrt/package/base-files/default/bin/firstboot b/branches/whiterussian/openwrt/package/base-files/default/bin/firstboot
--- a/branches/whiterussian/openwrt/package/base-files/default/bin/firstboot
+++ b/branches/whiterussian/openwrt/package/base-files/default/bin/firstboot
@@ -53,6 +53,12 @@ mountdp() { # <device> <mount_point> <ignored> <fs>
 	exit 0
 }
 
+[ -z "$rom" ] && {
+	echo "You do not have a squashfs partition; aborting"
+	echo "(firstboot cannot be run on jffs2 based firmwares)"
+	exit 1
+}
+
 [ "$1" = "switch2jffs" ] && {
 	#2nd stage
 	mtd erase OpenWrt
@@ -70,12 +76,6 @@ mountdp() { # <device> <mount_point> <ignored> <fs>
 }
 
 # script run manually
-[ -z "$rom" ] && {
-	echo "You do not have a squashfs partition; aborting"
-	echo "(firstboot cannot be run on jffs2 based firmwares)"
-	exit 1
-}
-
 [ \! -z "$jffs" ] && {
 	echo "firstboot has already been run"
 	echo "jffs2 partition is mounted, only resetting files"
