clean up firstboot & mount_root; fix tmpfs sizes on low ram
git-svn-id: svn://svn.openwrt.org/openwrt@3523 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/branches/whiterussian/openwrt/package/base-files/default/bin/firstboot b/branches/whiterussian/openwrt/package/base-files/default/bin/firstboot
--- a/branches/whiterussian/openwrt/package/base-files/default/bin/firstboot
+++ b/branches/whiterussian/openwrt/package/base-files/default/bin/firstboot
@@ -33,55 +33,56 @@ dupe() { # <new_root> <old_root>
 }
 
 pivot() { # <new_root> <old_root>
-	pivot_root $1 $1$2
-	mount none /proc -t proc
-	umount $2/proc
-	mount -o move $2/dev /dev
-	mount -o move $2/tmp /tmp
+	mount -o move /proc $1/proc && \
+	pivot_root $1 $1$2 && {
+		mount -o move $2/dev /dev
+		mount -o move $2/tmp /tmp
+	}
 }
 
 mountdp() { # <device> <mount_point> <ignored> <fs>
-	mount $1 $2 -t $4
-	dupe $2 $rom
-	pivot $2 /rom
+        dev=$1; mnt=$2; shift 2; opt=$*
+	mount $dev $mnt $opt
+	dupe $mnt $rom
+	pivot $mnt /rom
 }
 
-# script run by mount_root
-[ "$1" = "ramoverlay" ] && {
-	#1st stage
-	mountdp none /mnt -t tmpfs
-	exit 0
+ramoverlay() {
+	mkdir -p /tmp/root
+	mountdp /tmp/root /mnt -o bind
 }
 
-[ -z "$rom" ] && {
-	echo "You do not have a squashfs partition; aborting"
-	echo "(firstboot cannot be run on jffs2 based firmwares)"
-	exit 1
-}
+[ "${0##*/}" = "firstboot" ] && {
+	[ -z "$rom" ] && {
+		echo "You do not have a squashfs partition; aborting"
+		echo "(firstboot cannot be run on jffs2 based firmwares)"
+		exit 1
+	}
 
-[ "$1" = "switch2jffs" ] && {
-	#2nd stage
+	[ "$1" = "switch2jffs" ] && {
+		mtd erase OpenWrt
+		mount -o remount,ro none / # try to avoid fs changing while copying
+		mount -o bind / /mnt
+		mount /dev/mtdblock/4 /rom/jffs -t jffs2
+		echo -n "copying files ... "
+		cp -a /mnt/* /rom/jffs
+		umount /mnt
+		echo "done"
+		pivot /rom /mnt
+		mount -o move /mnt /tmp/root
+		pivot /jffs /rom
+		jffs2root --clean
+		exit 0
+	}
+
+	# script run manually
+	[ \! -z "$jffs" ] && {
+		echo "firstboot has already been run"
+		echo "jffs2 partition is mounted, only resetting files"
+		dupe $jffs $rom
+		exit 0
+	}
+
 	mtd erase OpenWrt
-	mount -o remount,ro none / # try to avoid fs changing while copying
-	mount -o bind / /mnt
-	mount /dev/mtdblock/4 /rom/jffs -t jffs2
-	echo -n "copying files ... "
-	cp -a /mnt/* /rom/jffs
-	umount /mnt
-	echo "done"
-	pivot /rom /mnt
-	pivot /jffs /rom
-	jffs2root --clean
-	exit 0
+	mountdp /dev/mtdblock/4 /jffs -t jffs2
 }
-
-# script run manually
-[ \! -z "$jffs" ] && {
-	echo "firstboot has already been run"
-	echo "jffs2 partition is mounted, only resetting files"
-	dupe $jffs $rom
-	exit 0
-}
-
-mtd erase OpenWrt
-mountdp /dev/mtdblock/4 /jffs -t jffs2
