[packages_10.03.2] mysql: merge r28083, r29176, r29199, r29908
git-svn-id: svn://svn.openwrt.org/openwrt@30184 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/branches/packages_10.03.2/libs/mysql/files/mysqld.init b/branches/packages_10.03.2/libs/mysql/files/mysqld.init
--- a/branches/packages_10.03.2/libs/mysql/files/mysqld.init
+++ b/branches/packages_10.03.2/libs/mysql/files/mysqld.init
@@ -1,29 +1,30 @@
 #!/bin/sh /etc/rc.common
-# Copyright (C) 2010 OpenWrt.org
+# Copyright (C) 2010-2011 OpenWrt.org
 
 START=95
 STOP=10
 
-PID=/var/run/mysqld.pid
-CMD=/usr/bin/mysqld
+SERVICE_DAEMONIZE=1
+SERVICE_WRITE_PID=1
+SERVICE_STOP_TIME=9
+
+error() {
+	echo "${initscript}:" "$@" 1>&2
+}
 
 start() {
 	local datadir=$(sed -n -e "s/^[[:space:]]*datadir[[:space:]]*=[[:space:]]*[\"']\?\([^\"']*\)[\"']\?/\1/p" /etc/my.cnf)
 	if [ ! -d "$datadir" ]; then
-		echo "Error: datadir in /etc/my.cnf ($datadir) doesn't exist"
+		error "Error: datadir '$datadir' in /etc/my.cnf doesn't exist"
 		return 1
-	elif [ ! -f "$datadir/mysql/tables_priv.MYD" ]; then
-		echo "Error: I didn't detect a privileges table, you might need to run mysql_install_db --force to initialize the system tables"
-		return 1
-	else
-		echo -n "Starting MySQL daemon... "
-		start-stop-daemon -x $CMD -b -S -- --pid-file=$PID
-		echo "done"
 	fi
+	if [ ! -f "$datadir/mysql/tables_priv.MYD" ]; then
+		error "Error: I didn't detect a privileges table, you might need to run mysql_install_db --force to initialize the system tables"
+		return 1
+	fi
+	service_start /usr/bin/mysqld
 }
 
 stop() {
-	echo -n "Stopping MySQL daemon... "
-	service_kill ${CMD##*/} $PID
-	echo "done"
+	service_stop /usr/bin/mysqld
 }
