packages/ndyndns: use new service functions
git-svn-id: svn://svn.openwrt.org/openwrt@29064 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/packages/net/ndyndns/files/ndyndns.init b/packages/net/ndyndns/files/ndyndns.init
--- a/packages/net/ndyndns/files/ndyndns.init
+++ b/packages/net/ndyndns/files/ndyndns.init
@@ -1,18 +1,21 @@
 #!/bin/sh /etc/rc.common
-# Copyright (C) 2007 OpenWrt.org
+# Copyright (C) 2007-2011 OpenWrt.org
 
 START=80
-DEFAULT=/etc/default/ndyndns
+
+include /lib/network
 
 start() {
-	[ -f $DEFAULT ] && . $DEFAULT
-
-	. /etc/functions.sh
-	include /lib/network
 	scan_interfaces
-	/usr/sbin/ndyndns -c $CHROOT -f $CONFIG -i $(config_get wan ifname) $OPTIONS
+	config_get wan_if 'wan' 'ifname'
+	[ -n "$wan_if" ] || return 1
+	[ -f /etc/ndyndns/ndyndns.conf ] || {
+		echo "$0: missing config file '/etc/ndyndns/ndyndns.conf'" 1>&2
+		return 1
+	}
+	service_start /usr/sbin/ndyndns -c /etc/ndyndns -f /etc/ndyndns/ndyndns.conf -i $wan_if
 }
 
 stop() {
-	killall ndyndns
+	service_stop /usr/sbin/ndyndns
 }
