vnstat: update init script to use latest service functions
This is just a simple patch to update vnstatd to use the latest
service functions.

Signed-off-by: Joe Roback <openwrt-devel@roback.cc>
Signed-off-by: Florian Fainelli <florian@openwrt.org>

git-svn-id: svn://svn.openwrt.org/openwrt@35233 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/packages/net/vnstat/files/vnstat.init b/packages/net/vnstat/files/vnstat.init
--- a/packages/net/vnstat/files/vnstat.init
+++ b/packages/net/vnstat/files/vnstat.init
@@ -65,13 +65,18 @@ start() {
 	config_load vnstat
 	config_foreach init_ifaces vnstat
 
-	/usr/sbin/vnstatd -d
+	SERVICE_PID_FILE="${pid}"
+	service_start /usr/sbin/vnstatd -d
 }
 
 stop() {
 	local pid="$(vnstat_option PidFile)"
-	[ -n "$pid" ] && {
-		service_kill vnstatd "$pid"
-		rm -f "$pid"
+
+	[ -n "$pid" ] || {
+		echo "Error: No PidFile set in vnstat.conf" >&2
+		exit 1
 	}
+
+	SERVICE_PID_FILE="${pid}"
+	service_stop /usr/sbin/vnstatd
 }
