port lots of init scripts over to rc.common (more to come)
git-svn-id: svn://svn.openwrt.org/openwrt@4917 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/packages/net/miau/files/S50miau b/packages/net/miau/files/S50miau
--- a/packages/net/miau/files/S50miau
+++ b/packages/net/miau/files/S50miau
@@ -1,4 +1,5 @@
-#!/bin/sh
+#!/bin/sh /etc/rc.common
+# Copyright (C) 2006 OpenWrt.org
 
 DEFAULT="/etc/default/miau"
 OPTIONS="-d /etc/miau/"
@@ -6,27 +7,24 @@ LOG_DIR="/var/log/miau"
 ERR_LOG="$LOG_DIR/error.log"
 OUT_LOG="$LOG_DIR/miau.log"
 
-[ -f $DEFAULT ] && . $DEFAULT
-[ "$ENABLE_MIAU" = "yes" ] || exit 0
+start() {
+	[ -f $DEFAULT ] && . $DEFAULT
+	[ "$ENABLE_MIAU" = "yes" ] || exit 0
+	[ -f /var/run/miau.pid ] && {
+		echo "[ERROR] miau is running"
+		exit 0
+	}
+	[ -d $LOG_DIR ] || mkdir -p $LOG_DIR 
+	/usr/bin/miau -f $OPTIONS > $OUT_LOG 2> $ERR_LOG &
+	PID=$!
+	sleep 1 
+	if [ -d /proc/$PID ]; then
+		echo $PID > /var/run/miau.pid 
+	else 
+		echo "[ERROR] Unable to run miau as a daemon"
+	fi
+}
 
-case $1 in
- start)
-  [ -f /var/run/miau.pid ] && echo "[ERROR] miau is running"
-  [ -f /var/run/miau.pid ] && exit 0
-  [ -d /var/run ] || mkdir -p /var/run
-  [ -d $LOG_DIR ] || mkdir -p $LOG_DIR 
-  /usr/bin/miau -f $OPTIONS > $OUT_LOG 2> $ERR_LOG &
-  PID=$!
-  sleep 1 
-  [ -d /proc/$PID ] && echo $PID > /var/run/miau.pid 
-  [ -d /proc/$PID ] || echo "[ERROR] Unable to run miau as a daemon"
-  ;;
- stop)
-  [ -f /var/run/miau.pid ] && kill $(cat /var/run/miau.pid) >/dev/null 2>&1 && rm /var/run/miau.pid
-  ;;
- *)
- echo "usage: $0 (start|stop)"
- exit 1
-esac
-
-exit $? 
+stop() {
+	[ -f /var/run/miau.pid ] && kill $(cat /var/run/miau.pid) >/dev/null 2>&1 && rm /var/run/miau.pid
+}
