[packages] sshtunnel: update to version 2
git-svn-id: svn://svn.openwrt.org/openwrt@23263 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/packages/net/sshtunnel/files/etc/init.d/sshtunnel b/packages/net/sshtunnel/files/etc/init.d/sshtunnel
--- a/packages/net/sshtunnel/files/etc/init.d/sshtunnel
+++ b/packages/net/sshtunnel/files/etc/init.d/sshtunnel
@@ -5,40 +5,82 @@ STOP=01
 
 PIDFILE="/tmp/run/sshtunnel"
 
-load_tunnel() {
-	config_get user $1 user
-	config_get hostname $1 hostname
-	config_get identity $1 identity
-	config_get remoteport $1 remoteport
-	config_get localport $1 localport
-	config_get options $1 options '-o ServerAliveCountMax=3 -o ServerAliveInterval=20 -o StrictHostKeyChecking=false'
-	config_get retrydelay $1 retrydelay "10"
-	[ "$cfgtype" = "tunnelL" ] && {
-		config_get localaddress $1 localaddress "127.0.0.1"
-		config_get remoteaddress $1 remoteaddress "*"
-	}
-	[ "$cfgtype" = "tunnelR" ] && {
-		config_get localaddress $1 localaddress "*"
-		config_get remoteaddress $1 remoteaddress "127.0.0.1"
-	}
+load_server() {
+	server="$1"
 
-	local error
-	[ -f "$identity" ] 	|| error="Identity file $identity not accessible"
-        [ -n "$user" ] 		|| error="please set user option"                                                                       
-        [ -n "$hostname" ] 	|| error="please set hostname option"                                                    
-        [ "$remoteport" -gt 0 -a "$localport" -gt 0 -a "$retrydelay" -ge 0 ] 	|| error="invalid configuration"
-	[ -n "$error" ] && { logger -p user.err -t "sshtunnel" "$cfgtype $1 not started - $error"; return; }
-
-	[ "$cfgtype" = "tunnelL" ] && {
-		args="-N -i $identity -o PasswordAuthentication=no -o ExitOnForwardFailure=yes $options -L $localaddress:$localport:$remoteaddress:$remoteport $user@$hostname"
-	}
-	[ "$cfgtype" = "tunnelR" ] && {
-		args="-N -i $identity -o PasswordAuthentication=no -o ExitOnForwardFailure=yes $options -R $remoteaddress:$remoteport:$localaddress:$localport $user@$hostname"
-	}
+	config_get user 	$1 user
+	config_get hostname 	$1 hostname
+	config_get debuglevel	$1 debuglevel	"0"
+	config_get retrydelay 	$1 retrydelay	"10"
+	config_get CheckHostIP 	$1 CheckHostIP
+	config_get Compression 	$1 Compression
+	config_get CompressionLevel 	$1 CompressionLevel
+	config_get IdentityFile		$1 IdentityFile
+	config_get LogLevel 		$1 LogLevel
+	config_get ServerAliveCountMax 	$1 ServerAliveCountMax
+	config_get ServerAliveInterval 	$1 ServerAliveInterval
+	config_get StrictHostKeyChecking $1 StrictHostKeyChecking
+	config_get TCPKeepAlive		$1 TCPKeepAlive
+	config_get VerifyHostKeyDNS 	$1 VerifyHostKeyDNS
 	
-	/usr/bin/sshtunnel.sh "$args" "$retrydelay" &
+	error=""
+        [ -n "$user" ] 		|| error="user is not set"                                                                       
+        [ -n "$hostname" ] 	|| error="${error:+$error; }hostname is not set"                                                    
+        [ "$retrydelay" -ge 0 ]	|| error="${error:+$error; }retrydelay must be a positive integer"
+	#[ -f "$IdentityFile" ] 	|| error="${error:+$error; }IdentityFile $IdentityFile not accessible"
+	#add validation for the rest of the parameters	
+	[ -n "$error" ] && { logger -p user.err -t "sshtunnel" "tunnels to $server not started - $error"; return; }
+        
+        tunnels_cmd=""
+	count=0
+        config_foreach load_tunnel tunnelR && config_foreach load_tunnel tunnelL
+	[ -n "$error" ] && { logger -p user.err -t "sshtunnel" "tunnels to $server not started - $error"; return; }
+	[ "$count" -eq 0 ] && { logger -p user.err -t "sshtunnel" "tunnels to $server not started - no tunnels defined"; return; }
+
+	cmd="${CheckHostIP:+-o CheckHostIP=$CheckHostIP }"
+	cmd="$cmd${CheckHostIP:+-o CheckHostIP=$CheckHostIP }"
+	cmd="$cmd${Compression:+-o Compression=$Compression }"
+	cmd="$cmd${CompressionLevel:+-o CompressionLevel=$CompressionLevel }"
+	cmd="$cmd${IdentityFile:+-o IdentityFile=$IdentityFile }"
+	cmd="$cmd${LogLevel:+-o LogLevel=$LogLevel }"
+	cmd="$cmd${ServerAliveCountMax:+-o ServerAliveCountMax=$ServerAliveCountMax }"
+	cmd="$cmd${ServerAliveInterval:+-o ServerAliveInterval=$ServerAliveInterval }"
+	cmd="$cmd${StrictHostKeyChecking:+-o StrictHostKeyChecking=$StrictHostKeyChecking }"
+	cmd="$cmd${TCPKeepAlive:+-o TCPKeepAlive=$TCPKeepAlive }"
+	cmd="$cmd${VerifyHostKeyDNS:+-o VerifyHostKeyDNS=$VerifyHostKeyDNS }"
+	cmd="$cmd""-o ExitOnForwardFailure=yes -o BatchMode=yes -nN $tunnels_cmd $user@$hostname"
+
+	/usr/bin/sshtunnel.sh "$cmd" "$retrydelay" "$server" &
 	echo $! >> "$PIDFILE".pids
-	logger -p user.info -t "sshtunnel" "started new $cfgtype $1 (pid=$!;retrydelay=$retrydelay)" 
+	logger -p user.info -t "sshtunnel" "started tunnels to $server (pid=$!;retrydelay=$retrydelay)" 
+}
+
+load_tunnel() {
+	config_get section_server $1 server
+	[ "$server" = "$section_server" ] || return 0 # continue to read next section if this is not for the current server
+	let count++ # count nr of valid sections to make sure there are at least one
+
+	config_get remoteport 	$1 remoteport
+	config_get localport	$1 localport
+	[ "$cfgtype" = "tunnelL" ] && {
+		config_get localaddress $1 localaddress "*"
+		config_get remoteaddress $1 remoteaddress
+	}
+	[ "$cfgtype" = "tunnelR" ] && {
+		config_get localaddress $1 localaddress
+		config_get remoteaddress $1 remoteaddress "*" 
+	}
+
+        [ "$remoteport" -gt 0 ] || error="remoteport must be a positive integer"                                                                       
+        [ "$localport" -gt 0 ] 	|| error="${error:+$error; }localpost must be a positive integer"
+	[ -n "$error" ] && return 1
+
+	[ "$cfgtype" = "tunnelL" ] && {
+		tunnels_cmd="${tunnels_cmd:+$tunnels_cmd }-L $localaddress:$localport:$remoteaddress:$remoteport"
+	}
+	[ "$cfgtype" = "tunnelR" ] && {
+		tunnels_cmd="${tunnels_cmd:+$tunnels_cmd }-R $remoteaddress:$remoteport:$localaddress:$localport"
+	}
 }
 
 stop() {
@@ -51,10 +93,11 @@ stop() {
 			start-stop-daemon -K -p "$PIDFILE"_"$pid".pid
 			kill $pid
 			logger -p daemon.info -t "sshtunnel[$pid]" "tunnel stopped"
+			rm "$PIDFILE"_"$pid".pid
 		done < "$PIDFILE".pids
-                
-                rm "$PIDFILE".pids
-                
+
+		rm "$PIDFILE".pids
+
                 logger -p user.info -t "sshtunnel" "all tunnels stopped"
         else
                 logger -p user.info -t "sshtunnel" "no tunnels running"
@@ -64,11 +107,13 @@ stop() {
 start() {
         [ -f "$PIDFILE".pids ] && stop
         
-        logger -p user.info -t "sshtunnel" "starting all tunnels"
-        
-        config_load sshtunnel
-        config_foreach load_tunnel tunnelR
-        config_foreach load_tunnel tunnelL
-       
-        logger -p user.info -t "sshtunnel" "all tunnels started"
+	config_load sshtunnel
+	if [ -n "$(uci show sshtunnel.@server[0])" ] # at least one server section exists
+	then        
+		logger -p user.info -t "sshtunnel" "starting all tunnels"
+		config_foreach load_server server       
+		logger -p user.info -t "sshtunnel" "all tunnels started"	
+	else
+		logger -p user.info -t "sshtunnel" "no servers defined"
+	fi
 }
